// 55-Introduccion-Vue.js-Creando-un-Proyecto/cotizador-prestamos-vue/src/components/Button.vue
<script setup>

const props = defineProps({
    operador: String,
});

</script>

<template>
    <button
        type="button"
        class="h-10 w-10 flex items-center justify-center font-bold bg-lime-500 rounded-full hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500 text-white text-2xl"
        @click="$emit('fn')"
    >{{operador}}</button>
</template>

// 54-Introducción-a-React-Creando-Un-Proyecto/cotizador-prestamos-react/src/components/Button.jsx
function Button(props) {
  return (
    <button
        type='button'
        className='h-10 w-10 flex items-center justify-center font-bold text-white bg-lime-500 text-2xl rounded-full hover:bg-lime-500 hover:outline-none hover:ring-2 hover:ring-offset-2 hover:ring-lime-500'
        onClick={props.fn}
    >{props.operador}</button>
  )
}

export default Button
